on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: " login to doxker hub "
        run: docker login --username sharifdhemy --password dckr_pat_HmFyt6Tvyk7-2kEXBLBmuY1YgCg
